# Generated by Django 2.2.5 on 2019-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20190928_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateTimeField(editable=False),
        ),
    ]
